language: node_js

node_js:
  - "10.14"

install:
  - npm install -g truffle@5.0.2
  - npm install

script:
  - npm test
  - if: branch = master OR branch = develop
      npm run test-tree

after_success:
  - npm run report-coverage
