codecov:
  notify:
    require_ci_to_pass: false

coverage:
  precision: 1
  round: up
  range: "30...100"
  status:
    target: 30
    project: yes
    patch: yes
    changes: no

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "header, diff"
  behavior: default
  require_changes: no
